In [ ]:
import math
from typing import List
import numpy as np


# Objectives

The learning objectives of this assignment are to:
1. implement feed-forward prediction for a single layer neural network 
2. implement training via back-propagation for a single layer neural network 

# Setup your environment

You will need to set up an appropriate coding environment on whatever computer
you expect to use for this assignment.
Minimally, you should install:

* [git](https://git-scm.com/downloads)
* [Python (version 3.8 or higher)](https://www.python.org/downloads/)
* [numpy](http://www.numpy.org/)
* [pytest](https://docs.pytest.org/)
* [pytest-timeout](https://pypi.org/project/pytest-timeout/)

# Check out the starter code

After accepting the assignment on GitHub Classroom, clone the newly created
repository to your local machine:
```
git clone https://github.com/ua-ista-457/back-propagation-<your-username>.git
```
You are now ready to begin working on the assignment.
You should do all your work in the default branch, `main`.

# Write your code

You will implement a simple single-layer neural network with sigmoid activations
everywhere.
This will include making predictions with a network via forward-propagation, and
training the network via gradient descent, with gradients calculated using
back-propagation.

You should read the documentation strings (docstrings) in each of methods in
`nn.py`, and implement the methods as described.
Write your code below the docstring of each method;
**do not delete the docstrings**.

The following objects and functions may come in handy:
* [numpy.ndarray.dot](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.dot.html)
* [numpy.ndarray.T](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html)
* [numpy.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html)
* [scipy.special.expit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.expit.html)

# Test your code for correctness

The tests in `test_nn.py` check that each method behaves as expected.
To run all the provided tests, run ``pytest`` from the directory containing
``test_nn.py``.
Initially, you will see output like:
```
============================= test session starts ==============================
...
collected 5 items

test_nn.py FFFFF                                                         [100%]

=================================== FAILURES ===================================
...
============================== 5 failed in 0.65s ===============================
```
This indicates that all tests are failing, which is expected since you have not
yet written the code for any of the methods.
Once you have written the code for all methods, you should instead see
something like:
```
============================= test session starts ==============================
...
collected 5 items

test_nn.py .....                                                         [100%]

============================== 5 passed in 0.47s ===============================
```

# Test your code for quality

In addition to the correctness tests, you should run `pylint nn.py` to check
for common code quality problems.
Pylint will check for adherence to
[standard Python style](https://www.python.org/dev/peps/pep-0008/),
good variable names, proper use of builtins like `enumerate`, etc.
If you use `scipy.special.expit`, you may also add the
`--extension-pkg-allow-list=scipy.special` option to silence a lint warning
from that package.
If there are no problems, you should see something like:
```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

# Submit your code

As you are working on the code, you should regularly `git commit` to save your
current changes locally.
You should also regularly `git push` to push all saved changes to the remote
repository on GitHub.
Make a habit of checking the "Feedback" pull request on the GitHub page for your
repository.
You should see all your pushed commits there, as well as the status of the
"checks".
If any correctness (pytest) or quality (pylint) tests are failing, you will see
"All checks have failed" at the bottom of the pull request.
If you want to see exactly which tests have failed, click on the "Details" link.
When you have corrected all problems, you should see "All checks have passed"
at the bottom of the pull request.

You do not need to do anything beyond pushing your commits to Github to submit
your assignment.
The instructional team will grade the code of the "Feedback" pull request, and
make detailed comments there.

# Grading

The points are allocated as follows:
* 80 points for passing all automated correctness (pytest) tests
* 10 points for passing all automated quality (pylint) tests
* 10 points for other quality issues:
using appropriate data structures,
using existing library functions whenever appropriate,
minimizing code duplication,
giving variables meaningful names,
documenting complex pieces of code, etc.

In [ ]:
def define_structure(X, Y):
    input_unit = X.shape[0] # size of input layer
    hidden_unit = 4 #hidden layer of size 4
    output_unit = Y.shape[0] # size of output layer
    return (input_unit, hidden_unit, output_unit)

(input_unit, hidden_unit, output_unit) = define_structure(np.asarray(X_train), np.asarray(y_train))
print("The size of the input layer is:  = " + str(input_unit))
print("The size of the hidden layer is:  = " + str(hidden_unit))
print("The size of the output layer is:  = " + str(output_unit))

In [1]:
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 31 19:27:33 2017
@author: rodol
"""
from numpy import exp, array, random, dot


class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(1)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))


if __name__ == "__main__":

    #Intialise a single neuron neural network.
    neural_network = NeuralNetwork()

    print ("Random starting synaptic weights: ")
    print (neural_network.synaptic_weights)

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print ("New synaptic weights after training: ")
    print (neural_network.synaptic_weights)

    # Test the neural network with a new situation.
    print ("Considering new situation [1, 0, 0] -> ?: ")
    print (neural_network.think(array([0, 1, 1])))
    

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Considering new situation [1, 0, 0] -> ?: 
[0.00786466]


In [9]:
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]])

In [41]:

import numpy as np

import sys


import numpy as np

class FCLayer:
    # input_size = number of input neurons
    # output_size = number of output neurons
    @classmethod
    def Random(cls, *layer_units: int):

        def uniform(n_in, n_out):
            epsilon = math.sqrt(6) / math.sqrt(n_in + n_out)
            return np.random.uniform(-epsilon, +epsilon, size=(n_in, n_out))

        pairs = zip(layer_units, layer_units[1:])
        return cls(*[uniform(i, o) for i, o in pairs])
    

    def __init__(self, *layer_weights: np.ndarray):
        random.seed(1)

        
        self.results = []
                
        self.weights = layer_weights
        self.bias = None #np.random.rand(1, output_size) - 0.5

    # returns output for a given input
    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = np.dot(self.input, self.weights) #+ self.bias
        return self.output

    # computes dE/dW, dE/dB for a given output_error=dE/dY. Returns input_error=dE/dX.
    def backward_propagation(self, output_error, learning_rate):
        input_error = np.dot(output_error, self.weights)
        weights_error = np.dot(self.input.T, output_error)
        # dBias = output_error

        # update parameters
        self.weights -= learning_rate * weights_error
        self.bias -= learning_rate * output_error
        return input_error
    
    
    def predict(self, input_data):
            # sample dimension first
        samples = len(input_data)
        result = []

        # run network over all samples
        for i in range(samples):
            # forward propagation
            output = input_data[i]
            #for layer in :
            output = self.forward_propagation(output)
            result.append(output)

        return result

In [42]:
layer = FCLayer()

In [44]:
layer.forward_propagation(training_set_inputs)

ValueError: shapes (4,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)

In [40]:
layer.backward_propagation(training_set_inputs, 0.01)

ValueError: shapes (4,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)

In [ ]:
# Forward Propagation functions

def linear_forward(value, weight):
    return np.matmul(value, weight.T)


def sigmoid_forward(value):
    return 1 / (1 + np.exp(-value))


def softmax_forward(trial):
    # return np.array([[np.exp(value)/np.sum(np.exp(row)) for value in row] for row in trial])
    return np.array([np.exp(value) / np.sum(np.exp(trial)) for value in trial])


def cross_entropy_forward(y_predicted, y_actual):
    # return np.sum(y_actual*np.log(y_predicted))/ y_predicted.shape[0]
    return - np.sum(y_actual * np.log(y_predicted))

In [ ]:


class SimpleNetwork:

    @classmethod
    def random(cls, *layer_units: int):

        def uniform(n_in, n_out):
            epsilon = math.sqrt(6) / math.sqrt(n_in + n_out)
            return np.random.uniform(-epsilon, +epsilon, size=(n_in, n_out))

        pairs = zip(layer_units, layer_units[1:])
        return cls(*[uniform(i, o) for i, o in pairs])

    def __init__(self, *layer_weights: np.ndarray):
           
        
    def predict(self, input_matrix: np.ndarray) -> np.ndarray:
    
    def predict_zero_one(self, input_matrix: np.ndarray) -> np.ndarray:
        
        
    def gradients(self,
                  input_matrix: np.ndarray,
                  output_matrix: np.ndarray) -> List[np.ndarray]:
      
    def train(self,
              input_matrix: np.ndarray,
              output_matrix: np.ndarray,
              iterations: int = 10,
              learning_rate: float = 0.1) -> None:
    


In [56]:
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]])

In [57]:
import matplotlib.pyplot as plt

class SimpleNetwork:
    """

    Parameters
    ------------
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight
      initialization.


    Attributes
    -----------
    w_ : 1d-array
      Weights after fitting.
    cost_ : list
      Sum-of-squares cost function value in each epoch.

    """
    @classmethod
    def Random(cls, *layer_units: int):

        def uniform(n_in, n_out):
            epsilon = math.sqrt(6) / math.sqrt(n_in + n_out)
            return np.random.uniform(-epsilon, +epsilon, size=(n_in, n_out))

        pairs = zip(layer_units, layer_units[1:])
        return cls(*[uniform(i, o) for i, o in pairs])

    def __init__(self, *layer_weights: np.ndarray):
        
        self.layer_weights = layer_weights
        self.results = []
        self.eta=0.01
        self.n_iter = 10
    def fit(self, X, y):
    
        for i in range(self.n_iter):
            
            net_input = self.net_input(X)
            # Please note that the "activation" method has no effect
            # in the code since it is simply an identity function. We
            # could write `output = self.net_input(X)` directly instead.
            # The purpose of the activation is more conceptual, i.e.,  
            # in the case of logistic regression (as we will see later), 
            # we could change it to
            # a sigmoid function to implement a logistic regression classifier.
            output = self.activation(net_input)
            errors = (y - output)
            self.w_[1:] += self.eta * X.T.dot(errors)
            self.w_[0] += self.eta * errors.sum()
            cost = (errors**2).sum() / 2.0
            self.cost_.append(cost)
    
    
    def gradients(self, X, y):
        
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
        self.cost_ = []
        
        
    
    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def activation(self, X):
        
        def sigmoid(X):
            """The sigmoid function."""
            return 1.0/(1.0+np.exp(-X))

        def sigmoid_prime(X):
            """Derivative of the sigmoid function."""
            return sigmoid(X)*(1-sigmoid(X))
            """Compute linear activation"""
            
        return X

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.activation(self.net_input(X)) >= 0.0, 1, -1)

In [61]:
def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return sigmoid(z)*(1-sigmoid(z))


Random weights at the start of training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New weights after training
[[5.39428067]
 [0.19482422]
 [0.34317086]]
Testing network on new examples ->
[0.99995873]


In [83]:
# Python program to implement a
# single neuron neural network
 
# import all necessary libraries
from numpy import exp, array, random, dot, tanh
 
# Class to create a neural
# network with single neuron
class NeuralNetwork():
     
    def __init__(self):
         
        # Using seed to make sure it'll 
        # generate same weights in every run
        random.seed(1)
         
        # 3x1 Weight matrix
        self.weight_matrix = 2 * random.random((3, 1)) - 1
        self.results = []

    
    def __sigmoid(self, x):
            return 1 / (1 + exp(-x))

        # The derivative of the Sigmoid function.
        # This is the gradient of the Sigmoid curve.
        # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)    
    
    
    
    def predict(self, input_matrix: np.ndarray):
        
        for i in range(self.NumOfSamples):
            # forward propagation
            output = input_matrix[i]
            #for layer in self.layers:
            output = self.gradients(input_matrix)
            self.results.append(output)
            

    def gradients(self, X, y):
            output = self.__sigmoid(dot(X, self.weight_matrix))
            error = training_set_outputs - output
            
            adjustment = np.matmul(training_set_inputs, error * self.__sigmoid_derivative(output))
            
            self.weight_matrix += adjustment
            
        
     
    # training the neural network.
    def train(self, train_inputs, train_outputs,
                            num_train_iterations, learn_rate):
                                 
        # Number of iterations we want to
        # perform for this set of input.
        for iteration in range(num_train_iterations):
            output = self.forward_propagation(train_inputs)
 
            # Calculate the error in the output.
            error = train_outputs - output
 
            # multiply the error by input and then
            # by gradient of tanh function to calculate
            # the adjustment needs to be made in weights
            adjustment = dot(train_inputs.T, error *
                             self.sigmoid_prime(output))
                              
            # Adjust the weight matrix
            self.weight_matrix += adjustment
 
# Driver Code
if __name__ == "__main__":
     
    neural_network = NeuralNetwork()
     
    print ('Random weights at the start of training')
    print (neural_network.weight_matrix)
 
    train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    train_outputs = array([[0, 1, 1, 0]]).T
 
    neural_network.train(train_inputs, train_outputs, 10000)
 
    print ('New weights after training')
    print (neural_network.weight_matrix)
 
    # Test the neural network with a new situation.
    print ("Testing network on new examples ->")
    print (neural_network.forward_propagation(array([1, 0, 0])))

Random weights at the start of training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


TypeError: sigmoid() takes 1 positional argument but 2 were given